spring:
  data:
    mongodb:
      uri: mongodb+srv://johnnyturesson:KnXmirC0LFkStKi5@moviecluster.t2epsfu.mongodb.net/?retryWrites=true&w=majority
      database: moviedb
  graphql:
    cors:
      allowed-origins: "*"
    graphiql:
      enabled: true

    schema:
      printer:
        enabled: true
      #data:
      # mongodb:
      #  database: moviedb
      # host: moviesearchcontainer
      #port: 27017

